"""update_analysis_table

Revision ID: fb6d204b68e5
Revises: e161e7467d64
Create Date: 2026-06-19 22:48:40.388789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb6d204b68e5'
down_revision: Union[str, Sequence[str], None] = 'e161e7467d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('resume_id', sa.Integer(), nullable=False))
    op.add_column('analyses', sa.Column('job_description', sa.Text(), nullable=False))
    op.add_column('analyses', sa.Column('missing_skills', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('recommendations', sa.Text(), nullable=True))
    op.alter_column('analyses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_analyses_resume_id'), 'analyses', ['resume_id'], unique=False)
    op.create_index(op.f('ix_analyses_user_id'), 'analyses', ['user_id'], unique=False)
    op.drop_constraint(op.f('analyses_user_id_fkey'), 'analyses', type_='foreignkey')
    op.create_foreign_key(None, 'analyses', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'analyses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('analyses', 'analysis_json')
    op.drop_column('analyses', 'jd_text')
    op.drop_column('analyses', 'resume_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('resume_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('analyses', sa.Column('jd_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('analyses', sa.Column('analysis_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.create_foreign_key(op.f('analyses_user_id_fkey'), 'analyses', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_analyses_user_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_resume_id'), table_name='analyses')
    op.alter_column('analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('analyses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('analyses', 'recommendations')
    op.drop_column('analyses', 'missing_skills')
    op.drop_column('analyses', 'job_description')
    op.drop_column('analyses', 'resume_id')
    # ### end Alembic commands ###
